sudo: required
services:
  - docker
language: node_js
node_js:
  - "12.16.3"
before_script:
  - docker-compose -f docker-compose.test.yml up -d postgres-test
  - sleep 5
script:
  - make test
cache:
  directories:
  - node_modules