version: "3.5"

services:
  bibcnrs-api-dev-server:
    image: node:14.21.2-bullseye-slim
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: development
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      BIBAPI_HOST: ${BIBAPI_HOST}
      BIB_CONTENT_DELIVERY_HOST: ${BIB_CONTENT_DELIVERY_HOST}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bibapi-dev
      POSTGRES_HOST: bibcnrs-dev-api-postgres
      REDIS_HOST: bibcnrs-dev-api-redis
      MAIL_SERVER_HOST: bibcnrs-dev-api-mail
      MAIL_SERVER_PORT: 1025
      EZ_UNPAYWALL_URL: "${EZ_UNPAYWALL_URL}"
      EZ_UNPAYWALL_KEY: "${EZ_UNPAYWALL_KEY}"
      DATABASE_URL: postgres://postgres:secret@bibcnrs-dev-api-postgres:5432/bibapi-dev
      METADORE_URL: "${METADORE_URL}"
      METADORE_API_KEY: "${METADORE_API_KEY}"
      DOAJ_URL: ${DOAJ_URL}
    ports:
      - "3000:3000"
    command: npm run dev
    networks:
      - bib-backend-network
      - bib-frontend-network

networks:
  bib-backend-network:
    external: true
  bib-frontend-network:
    external: true
