
node:
  image: node:4.1.2
  volumes:
    - .:/app
  environment:
    NODE_ENV: ${NODE_ENV}
  working_dir: /app

npm:
  extends:
    file: ./docker-compose.base.yml
    service: node
  environment:
    http_proxy: ${http_proxy}
    https_proxy: ${https_proxy}
    no_proxy: "localhost,127.0.0.1,"
  entrypoint: ['npm']

server:
  extends:
    file: ./docker-compose.base.yml
    service: node
  command: node launcher.js
  ports:
    - 3000:3000
