-- up:

CREATE TABLE IF NOT EXISTS institute_domain (
    domain_id       int NOT NULL REFERENCES domain(id) ON DELETE CASCADE,
    institute_id    int NOT NULL REFERENCES institute(id) ON DELETE CASCADE
);

-- down:

DROP TABLE institute_domain;

-- check:

SELECT EXISTS(
    SELECT *
    FROM information_schema.tables
    WHERE
        table_schema = 'public' AND
        table_name = 'institute_domain'
);
