-- up:

CREATE TABLE IF NOT EXISTS bib_user_domain (
    domain_id       int NOT NULL REFERENCES domain(id) ON DELETE CASCADE,
    bib_user_id     int NOT NULL REFERENCES bib_user(id) ON DELETE CASCADE,

    CONSTRAINT u_constraint UNIQUE (domain_id, bib_user_id)
);

-- down:

DROP TABLE bib_user_domain;

-- check:

SELECT EXISTS(
    SELECT *
    FROM information_schema.tables
    WHERE
        table_schema = 'public' AND
        table_name = 'bib_user_domain'
);
