-- up:

CREATE TABLE IF NOT EXISTS bib_user_unit (
    unit_id         int NOT NULL REFERENCES unit(id) ON DELETE CASCADE,
    bib_user_id     int NOT NULL REFERENCES bib_user(id) ON DELETE CASCADE,

    CONSTRAINT bib_user_unit_constraint UNIQUE (unit_id, bib_user_id)
);

-- down:

DROP TABLE bib_user_unit;

-- check:

SELECT EXISTS(
    SELECT *
    FROM information_schema.tables
    WHERE
        table_schema = 'public' AND
        table_name = 'bib_user_unit'
);
