-- up:

CREATE TABLE IF NOT EXISTS unit_institute (
    institute_id    int NOT NULL REFERENCES institute(id) ON DELETE CASCADE,
    unit_id     int NOT NULL REFERENCES unit(id) ON DELETE CASCADE,

    CONSTRAINT unit_institute_constraint UNIQUE (institute_id, unit_id)
);

-- down:

DROP TABLE unit_institute;

-- check:

SELECT EXISTS(
    SELECT *
    FROM information_schema.tables
    WHERE
        table_schema = 'public' AND
        table_name = 'unit_institute'
);
