-- up:

CREATE TABLE IF NOT EXISTS section_cn (
    id          serial primary key,
    code        varchar(255) NOT NULL,
    name        varchar(255) NOT NULL,
    comment     varchar(65535) NOT NULL,

    CONSTRAINT unique_section_cn_code UNIQUE (code)
);

-- down:

DROP TABLE section_cn;

-- check:

SELECT EXISTS(
    SELECT *
    FROM information_schema.tables
    WHERE
        table_schema = 'public' AND
        table_name = 'section_cn'
);
