-- up:

CREATE TABLE IF NOT EXISTS revue_community (
    revue_id     int NOT NULL REFERENCES revue(id) ON DELETE CASCADE,
    community_id    int NOT NULL REFERENCES community(id) ON DELETE CASCADE,

    CONSTRAINT revue_community_constraint UNIQUE (revue_id, community_id)
);

-- down:

DROP TABLE revue_community;

-- check:

SELECT EXISTS(
    SELECT *
    FROM information_schema.tables
    WHERE
        table_schema = 'public' AND
        table_name = 'revue_community'
);
